---
title: "Estatísticas descritivas"
format: html
editor: source
---

## Dados

```{r}
  bd_iels <- readRDS("../data_exerc/ex0_iels/base_iels1.RDS")

  library(readxl)
  dic_subset <- read_excel("../data_exerc/ex0_iels/dic.xlsx", sheet = "dic1")
  
  bd_iels <- as.data.frame(bd_iels)
  
  
  
```

## Variáveis 

```{r}
names(bd_iels)
str(bd_iels)
```

## Tabelas de frequencias e tabelas cruzadas

- pacote `sjmisc` [sjmisc](https://cran.r-project.org/web/packages/sjmisc/index.html)

```{r}
library(sjmisc)
library(labelled)
	
sjmisc::frq(bd_iels$ELPAQ0501)
sjmisc::frq(bd_iels$ELCHQ0501)

flat_table(bd_iels, ELPAQ0501, ELCHQ0501)



```

## Descritivas

- pacote `psych` [psych](https://cran.r-project.org/web/packages/psych/index.html)
- pacote  `skimr` [skimr](https://docs.ropensci.org/skimr/)
- pacote `gtsummary` [gtsummary](https://www.danieldsjoberg.com/gtsummary/)


```{r}
t1 <- psych::describe(bd_iels[ , 11:23])
str(t1)

names(t1)
rownames(t1)

t2 <- psych::describeBy(
 bd_iels[ , c(9, 11:23)], group = 1 )

str(t2)

str(t2$`1`)

t1b <- skimr::skim(bd_iels[ , 11:23])

str(t1b)

gtsummary::tbl_summary(bd_iels[ , 11:23])

```

## Correlações 

- pacote `correlation` [correlation](https://easystats.github.io/correlation/)
- pacote `corrr` [corrr](https://corrr.tidymodels.org)
- pacote `psych` 


```{r}
install.packages("correlation")
install.packages("insight")

t4 <- psych::corr.test(bd_iels[ , 11:23])

names(t4)

str(t4)

t4 <- t4$r

str(t4)
correlation::correlation(bd_iels[ , 11:23])
dimnames(t4)
corrr::correlate(bd_iels[ , 11:23])


```

```{r}

r <- corrr::correlate(bd_iels[ , 11:23])
corrr::rplot(r)
corrr::network_plot(r)

r <- correlation::correlation(bd_iels[ , 11:23])
summary(r)
plot(r)
correlation::cormatrix_to_excel(r, filename = "r.xlsx")

```

